### ISSUE TITLE
internal links

### ISSUE THREAD

**Issue by andrewpbray** [berkeley-scf/stat999-quarto#1]
Hey, this looks great!

Not sure if you've seen this, but you can simply link to docs using `lecture-1.qmd` instead of `lecture-1.html` and it will look into the qmd metadata for the output format to fill in the extension. Makes it a bit more flexible to subsequent format changes.

FWIW, I'm doing some changes to the Stat 20 website, including reorganizing the `_course-settings.yml` file to comport with the format of yours. That should allow you to incorporate into this template any features that would be useful to a broader audience like the auto-publishing and the separate student-facing (partial) and staff-facing (full) websites.

**Comment by paciorek** [comment]
@andrewpbray: in `_quarto.yml` I do link based on `lecture-1.qmd`. Can you say specifically where you noticed linking based on `lecture-1.html`?

Also, that's great to try to have synergy between this and your efforts. We're definitely interested in the auto-publishing and separate websites. So please point me to your changes once they are sufficiently far along and I'll see about adding features in here.

**Comment by andrewpbray** [comment]
I was looking in the the `_schedule.yml`. There are some `href`s on .pdf and .html files. Now that I look at it, though, are you thinking of these as links to pre-existing pdf or html files (vs ones created from qmd)?

**Comment by paciorek** [comment]
Yeah, the schedule stuff was just meant to link out to arbitrary hrefs, which might be pdf or html on the site or might be external. So that was intentional, but let me know if something else occurs to you.

**Comment by andrewpbray** [comment]
Gotcha. That makes sense.

One thing to just be aware of when doing that:

<https://quarto.org/docs/websites/website-tools.html#site-resources>

**Comment by ryanlovett** [comment]
@paciorek Do we need to declare those schedule-related links in the resources metadata value, per @andrewpbray 's note, or can we close this issue? There is a `test.pdf` linked to in the schedule, but the file doesn't exist in the repo, so it doesn't work as an example in this case.

**Comment by paciorek** [comment]
Andrew's link indicates quarto will auto-detect files it needs to put in `_site`. And I've just put `test.pdf` in the repo. So I think we can close this.
